[package]
name = "actix-sample"
version = "0.1.0"
authors = ["rui_iizumi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
actix-rt  = "1.0"
actix-files = "0.5.0"
diesel = "1.4.8"
